logo_text = "Yauheni Kazheka"

[meta]
description = "Personal site of Yauheni Kazheka featuring projects and writing."
defaultImage = "/images/og-default.jpeg"

[footer]
owner = "Yauheni Kazheka"

[social.gmail]
label = "Email"
url = "mailto:ykazheka@gmail.com"
aria_label = "Email Yauheni Kazheka"

[social.linkedin]
label = "LinkedIn"
url = "https://www.linkedin.com/in/yauheni-kazheka/"
aria_label = "View Yauheni Kazheka on LinkedIn"

[social.twitter]
label = "Twitter"
url = "https://twitter.com/ykazheka"
aria_label = "Follow Yauheni Kazheka on Twitter"
# Used in Twitter Card meta tags (without @)
handle = "ykazheka"

[social.github]
label = "GitHub"
url = "https://github.com/ykazheka"
aria_label = "Browse Yauheni Kazheka on GitHub"

[author]
name = "Yauheni Kazheka"
role = "Front-end Engineer"
bio = "Pragmatic frontend engineer who ships performant static experiences with Hugo and Tailwind."
photo = "images/author.jpg"
photo_alt = "Portrait of Yauheni Kazheka"
