baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Yauheni Kazheka'
enableRobotsTXT = true
canonifyURLs = true
enableGitInfo = true

[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]